config/routes.rb
Rails.application.routes.draw do
  resources :approvals
  devise_for :users
  resources :events

  resources :roles

  scope "/admin" do
    resources :users do
      collection do
        match 'update_collection', via: [:put, :patch]
      end
    end
  end
  root 'events#index'

end

app/models/approval.rb
class Approval < ActiveRecord::Base
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :set_approval, only: [:show, :edit, :update, :destroy]

  # GET /approvals
  # GET /approvals.json
  def index
    @approvals = Approval.all
    @users = User.where.not(:role_id => 2).order(:order)
    @event = Event.find_by_id(1)
  end

  # GET /approvals/1
  # GET /approvals/1.json
  def show
  end

  # GET /approvals/new
  def new
    @approval = Approval.new
  end

  # GET /approvals/1/edit
  def edit
  end

  # POST /approvals
  # POST /approvals.json
  def create
    @approval = Approval.new(approval_params)

    respond_to do |format|
      if @approval.save
        format.html { redirect_to @approval, notice: 'Approval was successfully created.' }
        format.json { render :show, status: :created, location: @approval }
      else
        format.html { render :new }
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /approvals/1
  # PATCH/PUT /approvals/1.json
  def update
    respond_to do |format|
      if @approval.update(approval_params)
        format.html { redirect_to @approval, notice: 'Approval was successfully updated.' }
        format.json { render :show, status: :ok, location: @approval }
      else
        format.html { render :edit }
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /approvals/1
  # DELETE /approvals/1.json
  def destroy
    @approval.destroy
    respond_to do |format|
      format.html { redirect_to approvals_url, notice: 'Approval was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_approval
      @approval = Approval.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def approval_params
      params.require(:approval).permit(:week)
    end
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/views/approvals/edit.html.erb
<h1>Editing Approval</h1>

<%= render 'form' %>

<%= link_to 'Show', @approval %> |
<%= link_to 'Back', approvals_path %>

app/views/approvals/index.html.erb
<!--<p id="notice"><%= notice %></p>

<h1>Listing Approvals</h1>

<table>
  <thead>
    <tr>
      <th>Week</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @approvals.each do |approval| %>
      <tr>
        <td><%= approval.week %></td>
        <td><%= link_to 'Show', approval %></td>
        <td><%= link_to 'Edit', edit_approval_path(approval) %></td>
        <td><%= link_to 'Destroy', approval, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Approval', new_approval_path %>-->

  <div class="sub_header">
    <span><span><span>Approvals : </span><span class="rbutton1"><< 1 </span><span class="rbutton2">2 </span><span class="rbutton3">3 </span><span class="rbutton4">4 >></span></span>
    <div class="button1 button">
      <div class="buttonLink">
        <%= link_to "", root_path %>
      </div>
    </div>
    <div class="button2 button">
      <div class="buttonLink">
        
      </div>
    </div>
    <% if current_user.role.name == "Admin" or current_user.role.name == "Admin/Employee" %>
    <div class="button3 button">
      <div class="buttonLink">
       <%= link_to '', approvals_path %> 
      </div>
    </div>
    <% end %>
  </div>
<div class="theadfix">
<table>
  <!--<thead>
    <tr>
      <th>USER</th>
      <th>SUNDAY</th>
      <th>MONDAY</th>
      <th>TUESDAY</th>
      <th>WEDNESDAY</th>
      <th>THURSDAY</th>
      <th>FRIDAY</th>
      <th>SATURDAY</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</table>-->
</div>
<div class="table">
<table>
<thead>
    <tr>
      <th class="userth">USER</th>
      <th>SUNDAY</th>
      <th>MONDAY</th>
      <th>TUESDAY</th>
      <th>WEDNESDAY</th>
      <th>THURSDAY</th>
      <th>FRIDAY</th>
      <th>SATURDAY</th>
      <th colspan="3"></th>
    </tr>
</thead>
</table>
</table>
<div class="table edit rotaone">
<div class="tr"><div class="td td_username userth"><%= @event.name %></div></div>
<% @users.each do |user| %>
<div class="tr">
  <%= form_for(user, :remote => true) do |f| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="td td_username username userth">
      <%= user.username %>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.sundayap %></span>
      <%= f.hidden_field :sunday, :value => user.sundayap %>
      <%= f.hidden_field :sundayap, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
    <span><%= user.mondayap %></span>
      <%= f.hidden_field :monday, :value => user.mondayap %>
      <%= f.hidden_field :mondayap, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.tuesdayap %></span>
      <%= f.hidden_field :tuesday, :value => user.tuesdayap %>
      <%= f.hidden_field :tuesdayap, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.wednesdayap %></span>
      <%= f.hidden_field :wednesday, :value => user.wednesdayap %>
      <%= f.hidden_field :wednesdayap, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.thursdayap %></span>
      <%= f.hidden_field :thursday, :value => user.thursdayap %>
      <%= f.hidden_field :thursdayap, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.fridayap %></span>
      <%= f.hidden_field :friday, :value => user.fridayap %>
      <%= f.hidden_field :fridayap, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.saturdayap %></span>
      <%= f.hidden_field :saturday, :value => user.saturdayap %>
      <%= f.hidden_field :saturdayap, :value => "" %>
    </div>
    </div>
    <div class="actions td">
      <%= f.submit :class => "sub" %>
    </div>
    
  <% end %>
  </div>
<% end %>
<div class="field">
  <button class="mastersub button_style">Approve</button>
</div>
</div>



<script type="text/javascript">
  $(".mastersub").click(function() {
    $(".sub").click();
    setTimeout(function(){
      window.location="/";
    }, 750);
  });
</script>

<div class="table edit rotatwo">
<div class="tr"><div class="td td_username userth"><%= @event.name02 %></div></div>
<% @users.each do |user| %>
<div class="tr">
  <%= form_for(user, :remote => true) do |f| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="td td_username username userth">
      <%= user.username %>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.sundayap02 %></span>
      <%= f.hidden_field :sunday02, :value => user.sundayap02 %>
      <%= f.hidden_field :sundayap02, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
    <span><%= user.mondayap02 %></span>
      <%= f.hidden_field :monday02, :value => user.mondayap02 %>
      <%= f.hidden_field :mondayap02, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.tuesdayap02 %></span>
      <%= f.hidden_field :tuesday02, :value => user.tuesdayap02 %>
      <%= f.hidden_field :tuesdayap02, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.wednesdayap02 %></span>
      <%= f.hidden_field :wednesday02, :value => user.wednesdayap02 %>
      <%= f.hidden_field :wednesdayap02, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.thursdayap02 %></span>
      <%= f.hidden_field :thursday02, :value => user.thursdayap02 %>
      <%= f.hidden_field :thursdayap02, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.fridayap02 %></span>
      <%= f.hidden_field :friday02, :value => user.fridayap02 %>
      <%= f.hidden_field :fridayap02, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.saturdayap02 %></span>
      <%= f.hidden_field :saturday02, :value => user.saturdayap02 %>
      <%= f.hidden_field :saturdayap02, :value => "" %>
    </div>
    </div>
    <div class="actions td">
      <%= f.submit :class => "sub2" %>
    </div>
    
  <% end %>
  </div>
<% end %>
<div class="field">
  <button class="mastersub2 button_style">Approve</button>
</div>
</div>



<script type="text/javascript">
  $(".mastersub2").click(function() {
    $(".sub2").click();
    setTimeout(function(){
      window.location="/";
    }, 750);
  });
</script>


<div class="table edit rotathree">
<div class="tr"><div class="td td_username userth"><%= @event.name03 %></div></div>
<% @users.each do |user| %>
<div class="tr">
  <%= form_for(user, :remote => true) do |f| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="td td_username username userth">
      <%= user.username %>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.sundayap03 %></span>
      <%= f.hidden_field :sunday03, :value => user.sundayap03 %>
      <%= f.hidden_field :sundayap03, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
    <span><%= user.mondayap03 %></span>
      <%= f.hidden_field :monday03, :value => user.mondayap03 %>
      <%= f.hidden_field :mondayap03, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.tuesdayap03 %></span>
      <%= f.hidden_field :tuesday03, :value => user.tuesdayap03 %>
      <%= f.hidden_field :tuesdayap03, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.wednesdayap03 %></span>
      <%= f.hidden_field :wednesday03, :value => user.wednesdayap03 %>
      <%= f.hidden_field :wednesdayap03, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.thursdayap03 %></span>
      <%= f.hidden_field :thursday03, :value => user.thursdayap03 %>
      <%= f.hidden_field :thursdayap03, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.fridayap03 %></span>
      <%= f.hidden_field :friday03, :value => user.fridayap03 %>
      <%= f.hidden_field :fridayap03, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.saturdayap03 %></span>
      <%= f.hidden_field :saturday03, :value => user.saturdayap03 %>
      <%= f.hidden_field :saturdayap03, :value => "" %>
    </div>
    </div>
    <div class="actions td">
      <%= f.submit :class => "sub3" %>
    </div>
    
  <% end %>
  </div>
<% end %>
<div class="field">
  <button class="mastersub3 button_style">Approve</button>
</div>
</div>



<script type="text/javascript">
  $(".mastersub3").click(function() {
    $(".sub3").click();
    setTimeout(function(){
      window.location="/";
    }, 750);
  });
</script>


<div class="table edit rotafour">
<div class="tr"><div class="td td_username userth"><%= @event.name04 %></div></div>
<% @users.each do |user| %>
<div class="tr">
  <%= form_for(user, :remote => true) do |f| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="td td_username username userth">
      <%= user.username %>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.sundayap04 %></span>
      <%= f.hidden_field :sunday04, :value => user.sundayap04 %>
      <%= f.hidden_field :sundayap04, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
    <span><%= user.mondayap04 %></span>
      <%= f.hidden_field :monday04, :value => user.mondayap04 %>
      <%= f.hidden_field :mondayap04, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.tuesdayap04 %></span>
      <%= f.hidden_field :tuesday04, :value => user.tuesdayap04 %>
      <%= f.hidden_field :tuesdayap04, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.wednesdayap04 %></span>
      <%= f.hidden_field :wednesday04, :value => user.wednesdayap04 %>
      <%= f.hidden_field :wednesdayap04, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.thursdayap04 %></span>
      <%= f.hidden_field :thursday04, :value => user.thursdayap04 %>
      <%= f.hidden_field :thursdayap04, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.fridayap04 %></span>
      <%= f.hidden_field :friday04, :value => user.fridayap04 %>
      <%= f.hidden_field :fridayap04, :value => "" %>
    </div>
    </div>
    <div class="td">
    <div class="draggable droppable">
      <span><%= user.saturdayap04 %></span>
      <%= f.hidden_field :saturday04, :value => user.saturdayap04 %>
      <%= f.hidden_field :saturdayap04, :value => "" %>
    </div>
    </div>
    <div class="actions td">
      <%= f.submit :class => "sub4" %>
    </div>
    
  <% end %>
  </div>
<% end %>
<div class="field">
  <button class="mastersub4 button_style">Approve</button>
</div>
</div>



<script type="text/javascript">
  $(".mastersub4").click(function() {
    $(".sub4").click();
    setTimeout(function(){
      window.location="/";
    }, 750);
  });
</script>

app/views/approvals/new.html.erb
<h1>New Approval</h1>

<%= render 'form' %>

<%= link_to 'Back', approvals_path %>

app/views/approvals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week:</strong>
  <%= @approval.week %>
</p>

<%= link_to 'Edit', edit_approval_path(@approval) %> |
<%= link_to 'Back', approvals_path %>