config/routes.rb
Rails.application.routes.draw do
  resources :approvals
  devise_for :users
  resources :events

  resources :roles

  scope "/admin" do
    resources :users do
      collection do
        match 'update_collection', via: [:put, :patch]
      end
    end
  end
  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_users
  before_action :set_user, except: [:index]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where(:approved => true)
    @users = User.where.not(:role_id => 2).order(:order)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_user
      @user = User.find(current_user.id)
    end

    def set_users
      @users = User.where.not(:role_id => 2).order(:order)
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def event_params
      params.require(:event).permit(:name, :user_id, :name02, :name03, :name04)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <div class="sub_header">
  <span><span>Rota : </span><span class="rbutton1"><< 1 </span><span class="rbutton2">2 </span><span class="rbutton3">3 </span><span class="rbutton4">4 >></span>
      <div class="button1 button">
      <div class="buttonLink">
        <%= link_to "", root_path %>
      </div>
    </div>
    <div class="button2 button">
      <div class="buttonLink">
        <%= link_to '', edit_event_path(event) %>
      </div>
    </div>
        <% if current_user.role.name == "Admin" or current_user.role.name == "Admin/Employee" %>
    <div class="button3 button">
      <div class="buttonLink">
       <%= link_to '', approvals_path %> 
      </div>
    </div>
    <% end %>
  </div>
<div class="theadfix">
<table>

</div>
<div class="table">

<table>
  <thead>
    <tr>
      <th class="userth">USER</th>
      <th>SUNDAY</th>
      <th>MONDAY</th>
      <th>TUESDAY</th>
      <th>WEDNESDAY</th>
      <th>THURSDAY</th>
      <th>FRIDAY</th>
      <th>SATURDAY</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody class="rotaone">
            <% if current_user.role.name == "Admin" or current_user.role.name == "Admin/Employee" %>
      <tr><td class="userth"><%= form_for(event, :remote => true) do |f| %><%= f.text_field :name, :value => event.name, :class => "text_in" %><%= f.submit "Update", :class => "namechange button_style" %><% end %></td></tr>
      <% else %>
      <tr><td class="userth"><%= event.name %></td></tr>
      <% end %>
      <% @users.each do |user| %>
        
        <tr class="tdb">
          <td class="username userth"><%= user.username %></td>
          <td><%= user.sunday %></td>
          <td><%= user.monday %></td>
          <td><%= user.tuesday %></td>
          <td><%= user.wednesday %></td>
          <td><%= user.thursday %></td>
          <td><%= user.friday %></td>
          <td><%= user.saturday %></td>
        </tr>
          
        
      <% end %>
  </tbody>
  <tbody class="rotatwo">    
      <% if current_user.role.name == "Admin" or current_user.role.name == "Admin/Employee" %>
      <tr><td class="userth"><%= form_for(event, :remote => true) do |f| %><%= f.text_field :name02, :value => event.name02, :class => "text_in" %><%= f.submit "Update", :class => "namechange button_style" %><% end %></td></tr>
      <% else %>
      <tr><td class="userth"><%= event.name02 %></td></tr>
      <% end %>
    <!--<tr>
      <th class="userth extraheads_l">USER</th>
      <th class="extraheads">SUNDAY</th>
      <th class="extraheads">MONDAY</th>
      <th class="extraheads">TUESDAY</th>
      <th class="extraheads">WEDNESDAY</th>
      <th class="extraheads">THURSDAY</th>
      <th class="extraheads">FRIDAY</th>
      <th class="extraheads_r">SATURDAY</th>
      <th colspan="3"></th>
    </tr>-->

      <% @users.each do |user| %>
        
        <tr class="tdb">
          <td class="username userth"><%= user.username %></td>
          <td><%= user.sunday02 %></td>
          <td><%= user.monday02 %></td>
          <td><%= user.tuesday02 %></td>
          <td><%= user.wednesday02 %></td>
          <td><%= user.thursday02 %></td>
          <td><%= user.friday02 %></td>
          <td><%= user.saturday02 %></td>
        </tr>
          
        
      <% end %>
  </tbody>
  <tbody class="rotathree">
            <% if current_user.role.name == "Admin" or current_user.role.name == "Admin/Employee" %>
      <tr><td class="userth"><%= form_for(event, :remote => true) do |f| %><%= f.text_field :name03, :value => event.name03, :class => "text_in" %><%= f.submit "Update", :class => "namechange button_style" %><% end %></td></tr>
      <% else %>
      <tr><td class="userth"><%= event.name03 %></td></tr>
      <% end %>
      <!--<tr>
      <th class="userth extraheads_l">USER</th>
      <th class="extraheads">SUNDAY</th>
      <th class="extraheads">MONDAY</th>
      <th class="extraheads">TUESDAY</th>
      <th class="extraheads">WEDNESDAY</th>
      <th class="extraheads">THURSDAY</th>
      <th class="extraheads">FRIDAY</th>
      <th class="extraheads_r">SATURDAY</th>
      <th colspan="3"></th>
    </tr>-->
      <% @users.each do |user| %>
        
        <tr class="tdb">
          <td class="username userth"><%= user.username %></td>
          <td><%= user.sunday03 %></td>
          <td><%= user.monday03 %></td>
          <td><%= user.tuesday03 %></td>
          <td><%= user.wednesday03 %></td>
          <td><%= user.thursday03 %></td>
          <td><%= user.friday03 %></td>
          <td><%= user.saturday03 %></td>
        </tr>
          
        
      <% end %>
  </tbody>
  <tbody class="rotafour">
            <% if current_user.role.name == "Admin" or current_user.role.name == "Admin/Employee" %>
      <tr><td class="userth"><%= form_for(event, :remote => true) do |f| %><%= f.text_field :name04, :value => event.name04, :class => "text_in " %><%= f.submit "Update", :class => "namechange button_style" %><% end %></td></tr>
      <% else %>
      <tr><td class="userth"><%= event.name04 %></td></tr>
      <% end %>
              <!--<tr>
      <th class="userth extraheads_l">USER</th>
      <th class="extraheads">SUNDAY</th>
      <th class="extraheads">MONDAY</th>
      <th class="extraheads">TUESDAY</th>
      <th class="extraheads">WEDNESDAY</th>
      <th class="extraheads">THURSDAY</th>
      <th class="extraheads">FRIDAY</th>
      <th class="extraheads_r">SATURDAY</th>
      <th colspan="3"></th>
    </tr>-->
      <% @users.each do |user| %>
        
        <tr class="tdb">
          <td class="username userth"><%= user.username %></td>
          <td><%= user.sunday04 %></td>
          <td><%= user.monday04 %></td>
          <td><%= user.tuesday04 %></td>
          <td><%= user.wednesday04 %></td>
          <td><%= user.thursday04 %></td>
          <td><%= user.friday04 %></td>
          <td><%= user.saturday04 %></td>
        </tr>
          
        
      <% end %>
      <!--<td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>

    
  </tbody>
</table>
</div>
<% end %>
<br>
<script type="text/javascript">
  $(".namechange").click(function() {
    setTimeout(function(){
      window.location="/";
    }, 750);
  });
</script>
<!--<%= link_to 'New Event', new_event_path %>-->

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>